### ISSUE TITLE
Incompatible with ue4.17.2

### ISSUE THREAD

**Issue by ParmuSingh** [getnamo/tensorflow-ue4-examples#14]
Plugins cannot be added in my version of ue4.

Screenshot : https://i.imgur.com/lRWWZGU.png

EDIT: Tried 4.19.0. Still doesn't work. Screenshot added.

**Comment by getnamo** [comment]
Did you follow the instructions in the readme https://github.com/getnamo/tensorflow-ue4-examples#setup ?

For 4.17 you should use the 0.2.1 examples release https://github.com/getnamo/tensorflow-ue4-examples/releases/tag/0.2.1 with the matching plugin release which is v0.4.1 https://github.com/getnamo/tensorflow-ue4/releases/tag/0.4.1. It's important you download the .7z file for cpu _or_ gpu which contains all prebuilt dlls for each plugin.

**Comment by ParmuSingh** [comment]
closing cause shifted to https://github.com/getnamo/tensorflow-ue4/issues/23

sorry for posing twice.
