### ISSUE TITLE
UEPyFSoftSkinVertex.h(15): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

### ISSUE THREAD

**Issue by mrG7** [getnamo/tensorflow-ue4-examples#15]
Comes bundled with these other errors,

1>d:\unrealengine-4.19.2-release\tensorflowexamples\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(15): error C3646: 'ss_vertex': unknown override specifier

1>d:\unrealengine-4.19.2-release\tensorflowexamples\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(15): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int

1>d:\unrealengine-4.19.2-release\tensorflowexamples\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(22): error C2065: 'FSoftSkinVertex': undeclared identifier

**Comment by getnamo** [comment]
see my reply on https://github.com/getnamo/tensorflow-ue4-examples/issues/16, same question

**Comment by mrG7** [comment]
UnrealEnginePython @ b488657	
socketio-client-ue4 @ bc97212	
tensorflow-ue4 @ aa681f8

Those are the branches I am using, as they are linked from your project.

**Comment by getnamo** [comment]
retry on latest release https://github.com/getnamo/tensorflow-ue4-examples/releases/tag/0.4.1 with https://github.com/getnamo/tensorflow-ue4/releases/tag/0.10.1 plugin, these package correctly and should compile under development or editor. If problem still persists, re-open issue.
