### ISSUE TITLE
TensorFlowBlueprintLibrary.cpp(166): error C2039: 'Source': is not a member of 'UTextureRenderTarget2D'

### ISSUE THREAD

**Issue by mrG7** [getnamo/tensorflow-ue4-examples#16]
1>D:\UnrealEngine-4.19.2-release\TensorFlowExamples\Plugins\tensorflow-ue4\Source\TensorFlow\Private\TensorFlowBlueprintLibrary.cpp(166): error C2039: 'Source': is not a member of 'UTextureRenderTarget2D'
1>D:\UnrealEngine-4.19.2-release\TensorFlowExamples\Plugins\tensorflow-ue4\Intermediate\Build\Win64\TensorFlowExamples\Inc\TensorFlow\TensorFlowBlueprintLibrary.generated.h(11): note: see declaration of 'UTextureRenderTarget2D'
1>D:\UnrealEngine-4.19.2-release\TensorFlowExamples\Plugins\tensorflow-ue4\Source\TensorFlow\Private\TensorFlowBlueprintLibrary.cpp(166): error C2228: left of '.UnlockMip' must have class/struct/union

**Comment by getnamo** [comment]
Do you have a context for this error? What combination of plugin + example project leads to this error and is it when your packaging or building for editor? etc. The more info you provide, the easier it is for me to replicate the error.

**Comment by mrG7** [comment]
I am using Release 4.19.2, simply trying to build the project so I can take a look. What specific version of the engine did you run this with? 

missing type specifier - int assumed. Note: C++ does not support default-int

Is the main error, do you have any special settings for Visual Studio 2017?

**Comment by mrG7** [comment]
I get this before it fails,

1>UnrealBuildTool : warning : d:\UnrealEngine-4.19.2-release\TensorflowExample\Plugins\tensorflow-ue4\Source\TensorFlow\TensorFlow.Build.cs(36,4) : warning CS0618: 'UnrealBuildTool.ModuleRules.RuntimeDependencyList.Add(UnrealBuildTool.ModuleRules.RuntimeDependency)' is obsolete: 'Constructing a RuntimeDependency object is deprecated. Call RuntimeDependencies.Add() with the path to the file to stage.'


1>UnrealBuildTool : warning : d:\UnrealEngine-4.19.2-release\TensorflowExample\Plugins\UnrealEnginePython\Source\UnrealEnginePython\UnrealEnginePython.Build.cs(230,5) : warning CS0618: 'UnrealBuildTool.ModuleRules.RuntimeDependencyList.Add(UnrealBuildTool.ModuleRules.RuntimeDependency)' is obsolete: 'Constructing a RuntimeDependency object is deprecated. Call RuntimeDependencies.Add() with the path to the file to stage.'

**Comment by mrG7** [comment]
So basically, this issue involves UEPyFSoftSkinVertex.h Line 15 and 22

1>d:\unrealengine-4.19.2-release\tensorflowexample\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(15): error C3646: 'ss_vertex': unknown override specifier
1>d:\unrealengine-4.19.2-release\tensorflowexample\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(15): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>d:\unrealengine-4.19.2-release\tensorflowexample\plugins\unrealenginepython\source\unrealenginepython\private\Wrappers/UEPyFSoftSkinVertex.h(22): error C2065: 'FSoftSkinVertex': undeclared identifier

**Comment by mrG7** [comment]
Should we building with Development Editor or just Development (or other)?

**Comment by getnamo** [comment]
Interesting, I typically only build the plugin separately for e.g. 4.19 and then just drag and drop it into the examples project, haven't tested compiling the plugin inside the example project together for a while. The error likely suggests a missing include if you build for e.g. development vs development editor. You may be able to resolve this by pulling from the upstream repo https://github.com/20tab/UnrealEnginePython as it's pretty active. I can only confirm that Development Editor should compile for 4.19. Working builds are always available at https://github.com/getnamo/tensorflow-ue4/releases

I'll look into dev vs editor maybe around ~4.20 update

**Comment by getnamo** [comment]
UTextureRenderTarget2D->source is an editor only feature and should not be needed. This has been fixed in https://github.com/getnamo/tensorflow-ue4/commit/98050247e2ec49de85d7da3e43c05c0fd6216d3f
