### ISSUE TITLE
4.23 Example not working  "LogPython: No module named 'TensorFlowComponent'"

### ISSUE THREAD

**Issue by CadBrad** [getnamo/tensorflow-ue4-examples#24]
I recently upgraded computers and am having trouble getting this working again.  I haven't change my specs all that much however this project used to work on my old computer and now it does not on my new one.

When I press play the level starts, doesn't throw any error messages, and lets me press the keyboard to change the numbers displayed.  It seems to skip entirely over the training portion and it no longer does anything when I press "F".  I noticed I was getting an error message in my output log, however I'm not sure how to correct it.  I understand python but am new to Unreal Engine.

Windows 10

Output Log below

LogTemp: Repeating last play command: Selected Viewport
LogBlueprintUserMessages: Early PlayInEditor Detection: Level '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel' has LevelScriptBlueprint '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel.Mnist' with GeneratedClass '/Game/ExampleAssets/Maps/Mnist.Mnist_C' with ClassGeneratedBy '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel.Mnist'
LogPlayLevel: PlayLevel: No blueprints needed recompiling
LogHMD: Initializing OVRPlugin session
LogHMD: Allocating Oculus 3296 x 1776 rendertarget swapchain
PIE: New page: PIE session: Mnist (May 12, 2021, 12:51:47 PM)
LogPlayLevel: Creating play world package: /Game/ExampleAssets/Maps/UEDPIE_0_Mnist
LogPlayLevel: PIE: StaticDuplicateObject took: (0.002097s)
LogAIModule: Creating AISystem for world Mnist
LogPlayLevel: PIE: World Init took: (0.000749s)
LogPlayLevel: PIE: Created PIE world by copying editor world from /Game/ExampleAssets/Maps/Mnist.Mnist to /Game/ExampleAssets/Maps/UEDPIE_0_Mnist.Mnist (0.002954s)
LogUObjectHash: Compacting FUObjectHashTables data took   1.17ms
LogInit: XAudio2 using 'Headphones (2- Rift S)' : 2 channels at 48 kHz using 16 bits per sample (channel mask 0x3)
LogInit: FAudioDevice initialized.
LogLoad: Game class is 'GameModeBase'
LogWorld: Bringing World /Game/ExampleAssets/Maps/UEDPIE_0_Mnist.Mnist up for play (max tick rate 0) at 2021.05.12-19.51.48
**LogPython: Error: No module named 'TensorFlowComponent'**
LogWorld: Bringing up level for play took: 0.001044
LogOnline: OSS: Creating online subsystem instance for: :Context_5
PIE: Play in editor start time for /Game/ExampleAssets/Maps/UEDPIE_0_Mnist 0.469
LogBlueprintUserMessages: Late PlayInEditor Detection: Level '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel' has LevelScriptBlueprint '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel.Mnist' with GeneratedClass '/Game/ExampleAssets/Maps/Mnist.Mnist_C' with ClassGeneratedBy '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel.Mnist'
SocketIOLog: SocketIO Connected with session: 0OyiC6LCh3RttJtxABOY
SocketIOLog: SocketIO 0OyiC6LCh3RttJtxABOY connected to namespace: /
LogBlueprintUserMessages: Early EndPlayMap Detection: Level '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel' has LevelScriptBlueprint '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel.Mnist' with GeneratedClass '/Game/ExampleAssets/Maps/Mnist.Mnist_C' with ClassGeneratedBy '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel.Mnist'
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogWorld: BeginTearingDown for /Game/ExampleAssets/Maps/UEDPIE_0_Mnist
LogWorld: UWorld::CleanupWorld for Mnist, bSessionEnded=true, bCleanupResources=true
LogPlayLevel: Display: Shutting down PIE online subsystems
LogBlueprintUserMessages: Late EndPlayMap Detection: Level '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel' has LevelScriptBlueprint '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel.Mnist' with GeneratedClass '/Game/ExampleAssets/Maps/Mnist.Mnist_C' with ClassGeneratedBy '/Game/ExampleAssets/Maps/Mnist.Mnist:PersistentLevel.Mnist'
LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
LogUObjectHash: Compacting FUObjectHashTables data took   1.03ms
LogPlayLevel: Display: Destroying online subsystem :Context_5
LogSlate: Took 0.000133 seconds to synchronously load lazily loaded font '../../../Engine/Content/Slate/Fonts/Roboto-Light.ttf' (167K)

**Comment by getnamo** [comment]
Points to missing plugin content, did you download the release? (7zip) did you place it in a short root location (less than. 240 char total for binaries)

**Comment by CadBrad** [comment]
I modified the standard download name (TensorFlowExamples-ue4.23-v0.7.0-noplugins (1)) to something smaller and deleted my existing Plugin folder and re-added the release (7zip).  Those combination of steps got it working for me, thanks for the quick reply.
