### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by sc1991327** [getnamo/tensorflow-ue4-examples#4]
Hello~

I'm lucky to find you are doing the work I want to do. But I have a problem in install this project.
My environment:
Win 10 + python 3.6 + VS 2015 + UE 4.12.5
I git this project and include the three plugin also.
https://github.com/getnamo/tensorflow-ue4
https://github.com/getnamo/UnrealEnginePython
https://github.com/getnamo/socketio-client-ue4
all are latest and put them in the /plugin/ also.
but have the compile problem in the SocketIOClientComponent.cpp

![image](https://cloud.githubusercontent.com/assets/5671048/23013441/8d79d766-f465-11e6-9816-9d86adb78e97.png)

could I solve this problem? I think I maybe lost a step or must change the plugin code?

**Comment by getnamo** [comment]
Currently still in the very early days of this plugin so YMMV.

All the current setup has been tested for 4.14 and python 3.5. Note that this project embeds the python executable, pip, and all pip dependencies inside the python plugin. Tensorflow dependency is then defined in: https://github.com/getnamo/tensorflow-ue4/blob/master/Content/Scripts/upymodule.json (just updated to 1.0.0 yesterday).

Try this release of the examples: https://github.com/getnamo/tensorflow-ue4-examples/releases and this release of the plugins: https://github.com/getnamo/tensorflow-ue4/releases/tag/0.0.9-pre. You can regenerate the .sln files from the project and recompile to ensure compilation works as expected.

**Comment by getnamo** [comment]
Try the new drag and drop release with everything included: https://github.com/getnamo/tensorflow-ue4-examples/releases/tag/0.1.2pre 

Closing the issue for now, re-open it if you still need to compile and the new build gives you the same errors.

Note these are still early days with early api, expect bugs and breaking issues!

Kindly add any issues from bugs, desired workflow, and documentation requests as you find or need them.
