### ISSUE TITLE
LINK : fatal error LNK1181: cannot open input file 'C:\Users\~\tensorflow-ue4-examples-master\Plugins\UnrealEnginePython\ThirdParty\Python35\Lib\Python35.lib'

### ISSUE THREAD

**Issue by mrG7** [getnamo/tensorflow-ue4-examples#5]
When trying the tensorflow-ue4-examples with 4.14.3, we get the following issue:

LINK : fatal error LNK1181: cannot open input file 'C:\User\~\ue4-Tensorflow\tensorflow-ue4-examples-master\Plugins\UnrealEnginePython\ThirdParty\Python35\Lib\Python35.lib'

I've tried all variations of the plugin UnrealEnginePython, I even tried to use the embedded Python35.

Can you provide version information? 

Thanks and awesome work, as always. 

-io

**Comment by getnamo** [comment]
I'm still working through the drag and drop installation of both the plugin and this example repository. See https://github.com/getnamo/tensorflow-ue4-examples/issues/3 for updates on the overall structure. Looking through my last releases, none of them have everything included yet. 

The general expected structure is to use e.g. embedded python 3.5 and add both include and lib under Plugins\UnrealEnginePython\ThirdParty\Python35 in their respective directories (/Include and /Lib). Then you add all the binaries and resources under Plugins\UnrealEnginePython\Binaries\Win64. Ideally all of that should be included in a release whenever I finally get everything working. To use pip you also should install pip in that binaries directory (there's a bat that does this, stay tuned for that magic release ...)

**Comment by getnamo** [comment]
the master branch when you raised the issue still had unfixed paths. In this particular instance it was missing these fixes: https://github.com/getnamo/UnrealEnginePython/commit/4d80ed9e853bb7401a70e5aad8db047256e2daf4

The fixes have been merged, I recommend you check out the latest release, it shouldn't need even need compilation: https://github.com/getnamo/tensorflow-ue4-examples/releases
