### ISSUE TITLE
Plugin issue for UE4.15.1 release

### ISSUE THREAD

**Issue by jresch** [getnamo/tensorflow-ue4-examples#6]
Hello,
Thanks for posting this, it is amazing! I have gotten this project to work before for python27, but I need python35 for what I'm trying to do. I've been trying to build this project but I have not been able to. I keep getting the following errors:

Any idea why these errors could pop up? 
Thanks so much for you time :)

>\plugins\unrealenginepython\source\unrealenginepython\private\UEPyFARFilter.h(11): error C2079: '<unnamed-tag>::filter' uses undefined struct 'FARFilter'

>\Plugins\socketio-client-ue4\Source\SIOJEditorPlugin\Private\SIOJ_BreakJson.cpp(34): error C2653: 'FEdGraphUtilities': is not a class or namespace name

>\Plugins\socketio-client-ue4\Source\SIOJEditorPlugin\Private\SIOJ_BreakJson.cpp(34): error C3861: 'GetNetFromPin': identifier not found

>\Plugins\socketio-client-ue4\Source\SIOJEditorPlugin\Private\SIOJ_BreakJson.cpp(121): error C2653: 'FEdGraphUtilities': is not a class or namespace name

>\Plugins\socketio-client-ue4\Source\SIOJEditorPlugin\Private\SIOJ_BreakJson.cpp(121): error C3861: 'GetNetFromPin': identifier not found

>\Plugins\UnrealEnginePython\Source\PythonConsole\Private\PythonConsoleModule.cpp(75): error C2228: left of '.GetDeveloperToolsLogCategory' must have class/struct/union

>Plugins\UnrealEnginePython\Source\PythonConsole\Private\PythonConsoleModule.cpp(76): error C2228: left of '.SetIcon' must have class/struct/union

ERROR : UBT error : Failed to produce item: C:\Users\jelly\Desktop\UE4151release\tensorflow\Plugins\UnrealEnginePython\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-UnrealEnginePython.lib

**Comment by getnamo** [comment]
Haven't seen those before, do note that the project uses a specific branch of the unrealenginepython plugin that favors embedded python 3.5 (this is my default platform). It's still a bit early for a release fix as I haven't gotten the drag and drop fully working, when that happens releases should be much easier to handle.

I've added this issue as a checklist for the first release. May be a few weeks before I carve out the time to fix all remaining issues.

**Comment by jresch** [comment]
Awesome, thanks so much!!

**Comment by getnamo** [comment]
Try the new drag and drop release with everything included: https://github.com/getnamo/tensorflow-ue4-examples/releases/tag/0.1.2pre 

Closing the issue for now, re-open it if you still need to compile and the new build gives you the same errors.

Note these are still early days with early api, still expect bugs and breaking api!

Kindly add any issues from bugs, desired workflow, and documentation requests as you find or need them.
