### ISSUE TITLE
fail open sample .uproject file with source code version of  unreal 4.17.1

### ISSUE THREAD

**Issue by idnemo** [getnamo/tensorflow-ue4-examples#9]
Error message says it the plugin build with a different engine version and can't enabled.  The plugins also build on 4.17.1 right?
And the solution will be I need to build plugin by myself? What's the correct way to do this?

**Comment by getnamo** [comment]
These are the correct instructions: https://github.com/getnamo/tensorflow-ue4-examples#setup

If you have a matching plugin version dragged in (0.4.1) and your project is C++ (you may just need to add dummy code class to convert the project from BP to C++), then if you build your project, the plugins should be automatically rebuild to your source version engine.

**Comment by sc1991327** [comment]
I use Ue4.17 and v0.4.1 plugin, but also failed.
No any error and warning in compiling and runnning error:

LogPython: Error: No module named 'tensorflow'
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "G:/UnrealProjects/TensorflowUE4/TestTensorflow/Plugins/tensorflow-ue4/Content/Scripts\TensorFlowComponent.py", line 2, in <module>
    import tensorflow as tf
LogPython: Error: ImportError: No module named 'tensorflow'

can not recognize module in unrealenginepython. what should I do?

**Comment by getnamo** [comment]
You may need to restart the project one extra time before pip correctly pulls the tensorflow module. Ensure that your network isn't blocked for pip packages.

**Comment by getnamo** [comment]
likely related to https://github.com/getnamo/tensorflow-ue4/issues/19

**Comment by getnamo** [comment]
addressed in readme: https://github.com/getnamo/tensorflow-ue4#no-module-named-tensorflow
